C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 0 100
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 100 200
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 200 300
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 300 400
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 400 500
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 500 600
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 600 700
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 700 800
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 800 900
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 900 1000
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 1000 1100
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 1100 1200
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 1200 1300
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 1300 1400
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 1400 1500
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 1500 1600
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 1600 1700
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 1700 1741