C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 0 100
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 100 200
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 200 300
C:\Graphics\Scene_Code\Descriptor\ZernikeMoments\ZernikeMoments01\ZernikeDescriptor\Release\ZernikeDescriptor 300 363